FROM redhat/ubi9-minimal

RUN yum update -y \
    && yum -y upgrade \
    && yum -y install git wget \
    && yum -y install R

RUN wget https://s3.amazonaws.com/rstudio-ide-build/server/rhel9/x86_64/rstudio-server-rhel-2023.03.0-daily-34-x86_64.rpm \
    && yum -y install rstudio-server-rhel-2023.03.0-daily-34-x86_64.rpm
