FROM fedora

RUN dnf update -y \
    && dnf -y upgrade \
    && dnf -y install git wget \
    && dnf -y install R

RUN wget https://s3.amazonaws.com/rstudio-ide-build/desktop/fedora36/x86_64/rstudio-2022.07.2-576-x86_64.rpm \
    && dnf -y install rstudio-2022.07.2-576-x86_64.rpm