FROM redhat/ubi9

RUN dnf update -y \
    && dnf -y install git wget

RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
    && dnf upgrade -y \
    && dnf -y install R

RUN wget https://s3.amazonaws.com/rstudio-ide-build/server/rhel9/x86_64/rstudio-server-rhel-2023.03.0-daily-34-x86_64.rpm \
    && dnf -y install rstudio-server-rhel-2023.03.0-daily-34-x86_64.rpm
