FROM fedora

RUN dnf update -y \
    && dnf -y upgrade \
    && dnf -y install git wget \
    && dnf -y install R

RUN wget https://rpmfind.net/linux/centos/8-stream/AppStream/aarch64/os/Packages/compat-openssl10-1.0.2o-4.el8.aarch64.rpm \
    && dnf -y compat-openssl10-1.0.2o-4.el8.aarch64.rpm \
    && wget https://download2.rstudio.org/server/rhel8/x86_64/rstudio-server-rhel-2022.12.0-353-x86_64.rpm \
    && dnf -y install rstudio-server-rhel-2022.12.0-353-x86_64.rpm